fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        entry: black -l 100 --quiet

  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        entry: isort --settings-path pyproject.toml
        additional_dependencies: [ toml ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-bugbear, flake8-typing-imports ]
        entry: flake8 --config setup.cfg

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        entry: bandit -x '*/.venv/*,*/tests/*,*/alembic/*'

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.0.3
    hooks:
      - id: detect-secrets
        args: [ '--baseline', '.secrets.baseline', 'force-use-all-plugins' ]
        exclude: .*\.lock*|.*\.md|.*\.ipynb|.secrets.baseline
